baseURL: "https://vigilant-hugle-3afd24.netlify.app/"
languageCode: "en-us"
title: "Krolla.Net"

module:
  imports:
    - path: github.com/vividvilla/ezhil

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 12
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  favicon: ''
  site_logo: ''
  description: The last theme you'll ever need. Maybe.
  facebook: ''
  twitter: ''
  instagram: 'https://www.instagram.com/krolla.amk/'
  youtube: ''
  github: 'https://github.com/drakenya/'
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: /images/sun_over_steel.jpg
  recent_posts_number: 2
  socialIcons:
    - name: instagram
    - url: https://www.instagram.com/krolla.amk/
