baseURL: "https://vigilant-hugle-3afd24.netlify.app/"
languageCode: "en-us"
title: "Krolla.Net"

module:
  imports:
    - path: github.com/zhaohuabing/hugo-theme-cleanwhite
    
site:
  title: "Krolla.Net Blog"

DefaultContentLanguage: en
SectionPagesMenu: main
Paginate: 12
googleAnalytics: ''
enableRobotsTXT: true
sitemap:
  changefreq: monthly
  priority: 0.5
  filename: sitemap.xml
params:
  author: Andrew Kroll
  header_image: /images/sun_over_steel.jpg
  favicon: ''
  site_logo: ''
  description: Ramblings on so much and yet so little.
  facebook: ''
  twitter: ''
  instagram: 'https://www.instagram.com/krolla.amk/'
  youtube: ''
  github: 'https://github.com/drakenya/'
  gitlab: ''
  linkedin: ''
  mastodon: ''
  slack: ''
  stackoverflow: ''
  rss: ''
  background_color_class: bg-black
  featured_image: /images/sun_over_steel.jpg
  recent_posts_number: 2
  socialIcons:
    - name: instagram
    - url: https://www.instagram.com/krolla.amk/
  social:
    email: krolla@gmail.com
    instagram: https://www.instagram.com/krolla.amk/
    flickr: https://www.flickr.com/photos/drakenya
  socials:
    - name: instagram
      link: https://www.instagram.com/krolla.amk/
    - name: flickr
      link: https://www.flickr.com/photos/drakenya
